// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $all_about_animals_slug_ from "./routes/all-about-animals/[slug].tsx";
import * as $api_comment from "./routes/api/comment.ts";
import * as $api_debug_navigations from "./routes/api/debug_navigations.ts";
import * as $api_webhooks_deploy from "./routes/api/webhooks/deploy.ts";
import * as $cdn_slug_ from "./routes/cdn/[slug].ts";
import * as $index from "./routes/index.tsx";
import * as $posts_slug_ from "./routes/posts/[slug].tsx";
import * as $LeaveReplyForm from "./islands/LeaveReplyForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/all-about-animals/[slug].tsx": $all_about_animals_slug_,
    "./routes/api/comment.ts": $api_comment,
    "./routes/api/debug_navigations.ts": $api_debug_navigations,
    "./routes/api/webhooks/deploy.ts": $api_webhooks_deploy,
    "./routes/cdn/[slug].ts": $cdn_slug_,
    "./routes/index.tsx": $index,
    "./routes/posts/[slug].tsx": $posts_slug_,
  },
  islands: {
    "./islands/LeaveReplyForm.tsx": $LeaveReplyForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
