// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $api_comment from "./routes/api/comment.ts";
import * as $index from "./routes/index.tsx";
import * as $page_page_ from "./routes/page/[page].tsx";
import * as $posts_slug_ from "./routes/posts/[slug].tsx";
import * as $posts_category_category_index from "./routes/posts/category/[category]/index.tsx";
import * as $posts_category_category_page_page_ from "./routes/posts/category/[category]/page/[page].tsx";
import * as $posts_tag_tag_index from "./routes/posts/tag/[tag]/index.tsx";
import * as $posts_tag_tag_page_page_ from "./routes/posts/tag/[tag]/page/[page].tsx";
import * as $LeaveReplyForm from "./islands/LeaveReplyForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/api/comment.ts": $api_comment,
    "./routes/index.tsx": $index,
    "./routes/page/[page].tsx": $page_page_,
    "./routes/posts/[slug].tsx": $posts_slug_,
    "./routes/posts/category/[category]/index.tsx":
      $posts_category_category_index,
    "./routes/posts/category/[category]/page/[page].tsx":
      $posts_category_category_page_page_,
    "./routes/posts/tag/[tag]/index.tsx": $posts_tag_tag_index,
    "./routes/posts/tag/[tag]/page/[page].tsx": $posts_tag_tag_page_page_,
  },
  islands: {
    "./islands/LeaveReplyForm.tsx": $LeaveReplyForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
